### ISSUE TITLE
eccezioni in fase di registrazione

### ISSUE THREAD

**Issue by fspegni** [idlweb/openordini#15]
gestisci eccezioni in fase di registrazione:
- persona con stesso slug esistente
- indirizzo email esistente
- username esistente

**Comment by idlweb** [comment]
Perché non gestisce l'emaol esistente?


Inviato da Samsung Mobile

-------- Messaggio originale --------
Da: Francesco Spegni <notifications@github.com> 
Data:22/01/2015  22:23  (GMT+01:00) 
A: idlweb/openordini <openordini@noreply.github.com> 
Oggetto: [openordini] eccezioni in fase di registrazione (#15) 

gestisci eccezioni in fase di registrazione:

persona con stesso slug esistente
indirizzo email esistente
username esistente

**Comment by fspegni** [comment]
username ed email esistenti sono gia' gestite. manca solo la persona con slug. gestire gli eventi in fase di registrazione con loggere dedicato (spedire via mail ad admin)
