### ISSUE TITLE
registrazione sessione A molte volte

### ISSUE THREAD

**Issue by fspegni** [idlweb/openordini#17]
se un utente spunta piu' checkbox, viene aggiunto alla stessa commissione (Sezione A) piu' volte.

**Comment by idlweb** [comment]
Risolto isolando:
# aggiungi a gruppi e commissioni

    if settings.REGISTRATION_AUTO_ADD_GROUP:

        is_registered_a = (register_subscription_date != None) and (says_is_psicologo_lavoro or says_is_psicologo_clinico or says_is_psicologo_forense) 
        
        if is_registered_a:
#                print "Utente registrato ..."
                i = Institution.objects.get(slug="sezione-a")
#                print "test verifica contenuto slug: %s ..." % (settings.COMMITTEE_SLUGS["psicologo_lavoro"])
                member_charge = InstitutionCharge(person=person, institution=i, start_date=register_subscription_date)
                member_charge.save()        

        if says_is_psicologo_lavoro:
            g,created = Group.objects.get_or_create(name=settings.SYSTEM_GROUP_NAMES["psicologo_lavoro"])
            g.user_set.add(user)

        if says_is_psicologo_clinico:
            g,created = Group.objects.get_or_create(name=settings.SYSTEM_GROUP_NAMES["psicologo_clinico"])
            g.user_set.add(user)
    
        if says_is_psicologo_forense:
            g,created = Group.objects.get_or_create(name=settings.SYSTEM_GROUP_NAMES["psicologo_forense"])
            g.user_set.add(user)

        is_registered_b = (register_subscription_date != None) and (says_is_dottore_tecniche_psicologiche) 

        if says_is_dottore_tecniche_psicologiche:
            g,created = Group.objects.get_or_create(name=settings.SYSTEM_GROUP_NAMES["dottore_tecniche_psicologiche"])
            g.user_set.add(user)

            if is_registered_b:
#                print "Utente registrato ..."
                i = Institution.objects.get(slug=settings.COMMITTEE_SLUGS["dottore_tecniche_psicologiche"])
#                print "test verifica contenuto slug: %s ..." % (settings.COMMITTEE_SLUGS["dottore_tecniche_psicologiche"])
                member_charge = InstitutionCharge(person=person, institution=i, start_date=register_subscription_date)
                member_charge.save()
