### ISSUE TITLE
riferimenti ad OM

### ISSUE THREAD

**Issue by fspegni** [idlweb/openordini#31]
1) In home page si leggono gli slogan: INFORMATI MONITORATI PARTECIPI. Non so se ci sia qualche refuso, ma a me qualcosa non quadra (dal punto di vista grammaticale e/o semantico); non so...

2) Ci sono ancora dei riferimenti (spuri, presumo) a OM, come in questa pagina:

**Comment by idlweb** [comment]
In serata provvedo. Grazie.


Inviato da Samsung Mobile

-------- Messaggio originale --------
Da: Francesco Spegni <notifications@github.com> 
Data:26/03/2015  16:38  (GMT+01:00) 
A: idlweb/openordini <openordini@noreply.github.com> 
Oggetto: [openordini] riferimenti ad OM (#31) 

1) In home page si leggono gli slogan: INFORMATI MONITORATI PARTECIPI. Non so se ci sia qualche refuso, ma a me qualcosa non quadra (dal punto di vista grammaticale e/o semantico); non so...

2) Ci sono ancora dei riferimenti (spuri, presumo) a OM, come in questa pagina:
