### ISSUE TITLE
Personalizzazione widget lato admin per fascicolo

### ISSUE THREAD

**Issue by idlweb** [idlweb/openordini#6]
Non viene visualizzata la personalizzazione in admin per l'applicazione 'actsfulfillments'

from django.contrib import admin
from django import forms
from django.forms import ModelForm
from .models import Fascicolo, InstitutionCharge

"""
class CustomerInstitutionForm(forms.ModelForm): 
    def __init__(self, *args, **kwargs):
        super(CustomerInstitutionForm, self).__init__(*args, **kwargs)
        wtf = InstitutionCharge.objects.filter();
        w = self.fields['recipient_set'].widget
        choices = []
        for choice in wtf:
            #choices.append((choice.id, choice.name))
            choices.append(choice.id)
        w.choices = choices
"""
class CustomerInstitutionForm(forms.ModelForm):
    class Meta:
        model = Fascicolo
        widgets = {
            'recipient_set': forms.SelectMultiple(attrs={'size': 24 })
        }

class FascicoloAdmin(admin.ModelAdmin):
    list_display = ("status", "approval_date", "publication_date","execution_date","initiative")
    #list_filter = ["approvazione", ]    
    #raw_id_fields = ["recipient_set", ]
    search_fields = ["acts_support__support_type", "acts_support__support_date", ]
    filter_horizontal = ('recipient_set',)
    form = CustomerInstitutionForm 

admin.site.register(Fascicolo, FascicoloAdmin)

**Comment by fspegni** [comment]
Attenzione: args è in realtà *args mentre *kwargs è **kwargs. Riprova dopo
la correzione
Il 03/Gen/2015 09:38 "idlweb" <notifications@github.com> ha scritto:

**Comment by idlweb** [comment]
E' l'editor di github che ha tolto i caratteri, ci sono. Il blocco a cui fai riferimento è comunque commentato a dover funzionare è:
class CustomerInstitutionForm(forms.ModelForm):
class Meta:
model = Fascicolo
widgets = {
'recipient_set': forms.SelectMultiple(attrs={'size': 24 })
}
che non sortisce effetti.

**Comment by idlweb** [comment]
Cosa strana, le guide riportano:
>>> from django.forms import ModelForm
>>> from myapp.models import Article
ma se non importo:
from django import forms
ho errore sul modulo, in pratica ModelForm sembra non essere caricato.

**Comment by idlweb** [comment]
da terminal il modulo si carica:
>>> dir (ModelForm)
['__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__getitem__', '__hash__', '__init__', '__iter__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__unicode__', '__weakref__', '_clean_fields', '_clean_form', '_get_changed_data', '_get_errors', '_get_media', '_get_validation_exclusions', '_html_output', '_post_clean', '_raw_value', '_update_errors', 'add_initial_prefix', 'add_prefix', 'as_p', 'as_table', 'as_ul', 'changed_data', 'clean', 'errors', 'full_clean', 'has_changed', 'hidden_fields', 'is_multipart', 'is_valid', 'media', 'non_field_errors', 'save', 'validate_unique', 'visible_fields']
>>>

**Comment by fspegni** [comment]
in effetti l'uso di filtered_horizontal rendeva tutto piu' complicato. il motivo per cui ho dovuto creare una estensione del widget FilteredSelectMultiple di django.admin.widgets e' che quello di default non prende l'argomento `attrs` passato al costruttore. la nostra estensione ora lo prende, e possiamo specificare il numero di righe da mostrare. ho testato e funziona

**Comment by idlweb** [comment]
committato?

**Comment by idlweb** [comment]
ok.
